spring.application.name=interviewpro-backend

spring.datasource.url=jdbc:mysql://localhost:3306/interviewpro
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080